project:
  type: book
  output-dir: docs
lang: pl

book:
  title: "Matematyczne podstway sieci neuronowych"
  author: "Piotr Dyszewski"
  search: true
  date: "6/8/2026"
  page-footer: "Copyright 2026, Piotr Dyszewski"
  downloads: [pdf]
  repo-url: https://github.com/pdyszewski
  cover-image: Cover/cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - 01_Supervised_Learning.qmd
    - 02_Artificial_Neurons.qmd
    - 03_Shallow_Networks.qmd
    - 04_Stochastic_Gradient_Descent.qmd
    - 05_Training.qmd
    - 06_Deep_Neural_Networks.qmd
    - 07_Initialization.qmd
    - 08_Convolutional_Neural_Networks.qmd
    - 09_Automatic_Differentiation_Backpropagation.qmd
    - 10_Adaptive_Learning_Rate_Algorithms.qmd
    - 11_Redukcja_wymiaru.qmd
    - 12_Autoenkodery.qmd
    - 13_Diffusion_Models.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



